export type { Itinerario } from './itinerario.interface'
export type { ResTransit } from './res-transit.interface'
export type { Transites } from './transites.interface'
export type { Tour } from './tour.interface'
export type { Place } from './place.interface'
export type { ResHotel } from './res-hotels.interface'
