export { actionsWeather } from './weather/actions-weather'
export { actionsTime } from './time/actions-time'
export { actionsTransit } from './transit/actions-transit'
export { actionsFoto } from './cronograma/actions-foto'
export { actionsFotosArray } from './cronograma/actions-fotos-array'
